# Read,Display and Save(write) Image

In [6]:
import numpy as np
import cv2

def main():
    imgpath = "C:\\Users\\Aung Thiha\\misc\\4.2.04.tif"
    outpath = "D:\\My Files\\Mechatronic Engineering\\Computer Vision\\Lena.png"
    cv2.namedWindow("Lena" , cv2.WINDOW_NORMAL)
    img = cv2.imread(imgpath)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    print(gray)
    cv2.imshow("Lena" , gray)
    #cv2.imwrite(outpath , img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
if __name__ == "__main__":
    main()
    print()

[[162 161 159 ... 168 170 141]
 [162 161 159 ... 168 170 141]
 [163 159 160 ... 158 151 116]
 ...
 [ 50  51  53 ...  81  92  91]
 [ 44  49  50 ...  93 101  98]
 [ 44  53  50 ... 101 102 106]]



# Accessing Image Properties

In [6]:
import cv2
import numpy

imgpath = "C:\\Users\\Aung Thiha\\misc\\4.2.04.tif"
img = cv2.imread(imgpath , -1)
print(img.shape)
print(img.size)
print(img.dtype)
print(img.ndim)
print(img)

(256, 256, 3)
196608
uint8
3
[[[125 137 226]
  [130 136 223]
  [118 133 226]
  ...
  [127 145 230]
  [122 148 232]
  [100 114 210]]

 [[125 137 226]
  [130 136 223]
  [118 133 226]
  ...
  [127 145 230]
  [122 148 232]
  [100 114 210]]

 [[124 138 226]
  [121 133 223]
  [117 134 226]
  ...
  [118 133 222]
  [108 125 217]
  [ 90  87 182]]

 ...

 [[ 61  28  90]
  [ 61  28  91]
  [ 63  29  97]
  ...
  [ 71  53 140]
  [ 73  62 158]
  [ 74  59 161]]

 [[ 60  20  85]
  [ 59  25  91]
  [ 62  26  94]
  ...
  [ 82  64 153]
  [ 81  69 172]
  [ 78  65 170]]

 [[ 57  22  82]
  [ 62  30  94]
  [ 61  25  95]
  ...
  [ 84  71 167]
  [ 78  68 178]
  [ 81  72 183]]]


## Color Layers Finding

In [ ]:
import cv2

img = cv2.imread("b.jfif")

red = img[:,:,2]               # red is third layer of image (inner layer)
green = img[:,:,1]             # green is second layer of image ( middle layer)
blue = img[:,:,0]              # blue is first layer of image (outer layer)

cv2.imshow("RGB",img)
cv2.imshow("Red",red)
cv2.imshow("Green",green)
cv2.imshow("Blue",blue)

cv2.waitKey(0)
cv2.destroyAllWindows()