# Color Tracking Example

#### To get other flags, just run following commands in your Python terminal

In [ ]:
import cv2
flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
print(flags)

#### Hue range is [0,79], Saturation range is [0,255] and Value range is [0,255])


### Only one color tracking

In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

for i in range(60):
    ret,background = cap.read()

while cap.isOpened()==True:
    #cv2.namedWindow("Aung Thiha",cv2.WINDOW_GUI_NORMAL)
    ret,frame = cap.read()
    
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    
    #green
    #low = np.array([[[55,170,130]]])
    #high = np.array([[[140,255,255]]])
    
    #red
    low_red = np.array(([165, 170, 130]))
    high_red = np.array(([255, 255, 255]))
    
    #blue
    low_blue = np.array([70, 170, 130])
    high_blue = np.array([160, 255, 255])
    
    
    mask_blue = cv2.inRange(hsv,low_blue,high_blue)
    mask_red = cv2.inRange(hsv,low_red,high_red)
    
    color_track = cv2.bitwise_and(frame,frame, mask= mask_red)
    
    cv2.imshow("Aung Thiha",frame)
    cv2.imshow("HSV" , color_track)
    k = cv2.waitKey(1) & 0XFF
    if k ==27:
        break

cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


###  Two Colors Tracking

In [2]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while cap.isOpened()==True:
    #cv2.namedWindow("Aung Thiha",cv2.WINDOW_GUI_NORMAL)
    ret,frame = cap.read()
    
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    
    #green
    #low = np.array([[[55,170,130]]])
    #high = np.array([[[140,255,255]]])
    
    #red
    low_red = np.array(([165, 170, 130]))
    high_red = np.array(([255, 255, 255]))
    
    #blue
    low_blue = np.array([70, 170, 130])
    high_blue = np.array([160, 255, 255])
    
    mask_blue = cv2.inRange(hsv,low_blue,high_blue)
    mask_red = cv2.inRange(hsv,low_red,high_red)
    
    color_track_blue = cv2.bitwise_and(frame,frame, mask= mask_blue)
    color_track_red = cv2.bitwise_and(frame,frame, mask= mask_red)
    
    red_blue_tracking = color_track_blue + color_track_red
    
    cv2.imshow("Aung Thiha",frame)
    cv2.imshow("HSV" , red_blue_tracking)
    k = cv2.waitKey(1) & 0XFF
    if k ==27:
        break

cap.release()
cv2.destroyAllWindows()

## How to find HSV values to track?

### Green color for HSV

In [15]:
import numpy as np

green = np.uint8([[[0,255,0 ]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print(hsv_green)

[[[ 60 255 255]]]


### Red color for HSV

In [7]:
import numpy as np

red = np.uint8([[[0,0,255]]])
hsv_red = cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
print(hsv_red)

[[[  0 255 255]]]


### Blue color for HSV

In [11]:
import numpy as np

blue = np.uint8([[[255,0,0]]])
hsv_blue = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print(hsv_blue)

[[[120 255 255]]]


In [ ]:
for (top, right, bottom, left), name in zip(face_locations, face_names):
        # Scale back up face locations since the frame we detected in was scaled to 1/4 size
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4

        cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

        # Draw a label with a name below the face
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

### Bitwise Functions

In [2]:
import cv2
import numpy as np

img1 = cv2.imread("C:\\Users\\Aung Thiha\\Computer Vision with Python\\Image Data Sets\\drawing_1.png")
img2 = cv2.imread("C:\\Users\\Aung Thiha\\Computer Vision with Python\\Image Data Sets\\drawing_2.png")

bit_and = cv2.bitwise_and(img2, img1)
bit_or = cv2.bitwise_or(img2, img1)
bit_xor = cv2.bitwise_xor(img1, img2)
bit_not = cv2.bitwise_not(img1)
bit_not2 = cv2.bitwise_not(img2)

cv2.imshow("img1", img1)
cv2.imshow("img2", img2)

cv2.imshow("bit_and", bit_and)
cv2.imshow("bit_or", bit_or)
cv2.imshow("bit_xor", bit_xor)
cv2.imshow("bit_not", bit_not)
cv2.imshow("bit_not2", bit_not2)


cv2.waitKey(0)
cv2.destroyAllWindows()