https://www.youtube.com/watch?v=6yVMpaIoxIU

https://www.youtube.com/watch?v=uDB2qGqnQ1g

https://www.youtube.com/watch?v=KEYzUP7-kkU

# Hough line Transform ( Normal )

In [5]:
import cv2
import numpy as np

cv2.namedWindow("Hough Line Transform",cv2.WINDOW_NORMAL)
img = cv2.imread("C:\\Users\\Aung Thiha\\Computer Vision with Python\\Image Data Sets\\line.png")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)

lines = cv2.HoughLines(edges,1,np.pi/180,50)

for rho,theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = np.cos(theta)*rho
    y0 = np.sin(theta)*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imshow("Hough Line Transform" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Probabilistic Hough Transform For Images

In the hough transform, you can see that even for a line with two arguments, it takes a lot of computation. Probabilistic Hough Transform is an optimization of Hough Transform we saw. It doesn’t take all the points into consideration, instead take only a random subset of points and that is sufficient for line detection. Just we have to decrease the threshold

In [39]:
import cv2
import numpy as np

cv2.namedWindow("Hough Line Transform",cv2.WINDOW_NORMAL)
img = cv2.imread("C:\\Users\\Aung Thiha\\Computer Vision with Python\\Image Data Sets\\line.png")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

edge = cv2.Canny(gray,50,150)

lines = cv2.HoughLinesP(edge,1,np.pi/180,30,maxLineGap = 200)
print(lines)

for i in lines:
    x1,y1,x2,y2 = i[0]
    cv2.line(img,(x1,y1),(x2,y2),(255,0,255),2)

cv2.imshow("Hough Line Transform" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 59 104 206 104]]

 [[ 59  36 206  36]]

 [[ 59 106 206 106]]

 [[ 59  34 206  34]]

 [[ 59 105  59  35]]

 [[204 103 204  37]]

 [[ 61 103  61  37]]

 [[206 105 206  35]]]
